### ISSUE TITLE
Qiskit 1.0 compatibility

### ISSUE THREAD

**Issue by mtreinish** [qiskit-community/dsm-swap#6]
### Steps to reproduce the problem

Install dsm-swap with qiskit >= 1.0.0

### What is the current behavior?

The current version of dsm-swap is incompatible with qiskit >= 1.0.0, the first issue is it lists it's dependency on qiskit-terra instead of qiskit which is mutually exclusive and will corrupt the venv. There might be other incompatibilities after that is
resolved, the migration guide for qiskit can be found here: https://docs.quantum.ibm.com/api/migration-guides/qiskit-1.0

### What is the expected behavior?

You can use dsm-swap with qiskit 1.0.0

**Comment by frankharkins** [comment]
I'll also use this issue to note that as of June we'll be removing any projects from the [Qiskit ecosystem](https://qiskit.github.io/ecosystem/) that aren't compatible with Qiskit 1.0.
